#!/bin/bash
echo "#################  pip3  ####################"
pip3 install --upgrade pip
echo "################# scoop #####################"
pip3 install --upgrade scoop
echo "################# scipy #####################"
pip3 install --upgrade scipy
echo "################# numpy #####################"
pip3 install --upgrade numpy
echo "################# networkx ##################"
pip3 install --upgrade networkx
echo "################# matplotlib  ###############"
pip3 install --upgrade matplotlib
echo "################ pandas ##################"
pip3 install --upgrade pandas
echo "#############################################"
