nohup python pick*py /home/mcb/malsha17/EvoByCompSel/parallel/Release-03/data/NETWORKS/Bacteria/RegulonDB/input/Bacteria-RegulonDB.txt > 1.txt & 
nohup python pick*py /home/mcb/malsha17/EvoByCompSel/parallel/Release-03/data/NETWORKS/Fly/BioGrid/input/Fly-BioGrid.txt > 2.txt & 
nohup python pick*py /home/mcb/malsha17/EvoByCompSel/parallel/Release-03/data/NETWORKS/Human/BioGrid/input/Human-BioGrid.txt > 3.txt & 
nohup python pick*py /home/mcb/malsha17/EvoByCompSel/parallel/Release-03/data/NETWORKS/Human/ENCODE-GM/input/Human-ENCODE-GM.txt > 4.txt & 
nohup python pick*py /home/mcb/malsha17/EvoByCompSel/parallel/Release-03/data/NETWORKS/Human/ENCODE-K562/input/Human-ENCODE-K562.txt > 5.txt & 
nohup python pick*py /home/mcb/malsha17/EvoByCompSel/parallel/Release-03/data/NETWORKS/Human/ENCODE-Proximal/input/Human-ENCODE-Proximal.txt > 6.txt & 
nohup python pick*py /home/mcb/malsha17/EvoByCompSel/parallel/Release-03/data/NETWORKS/Human/Liu/input/Human-Liu.txt > 7.txt & 
nohup python pick*py /home/mcb/malsha17/EvoByCompSel/parallel/Release-03/data/NETWORKS/Human/miRTarBase/input/Human-miRTarBase.txt > 8.txt & 
nohup python pick*py /home/mcb/malsha17/EvoByCompSel/parallel/Release-03/data/NETWORKS/Human/PSICQUIC/input/Human-PSICQUIC.txt > 9.txt & 
nohup python pick*py /home/mcb/malsha17/EvoByCompSel/parallel/Release-03/data/NETWORKS/Human/TRRUST/input/Human-TRRUST.txt > 10.txt & 
nohup python pick*py /home/mcb/malsha17/EvoByCompSel/parallel/Release-03/data/NETWORKS/Mouse/BioGrid/input/Mouse-BioGrid.txt > 11.txt & 
nohup python pick*py /home/mcb/malsha17/EvoByCompSel/parallel/Release-03/data/NETWORKS/Mouse/Liu/input/Mouse-Liu.txt > 12.txt & 
nohup python pick*py /home/mcb/malsha17/EvoByCompSel/parallel/Release-03/data/NETWORKS/Mouse/miRTarBase/input/Mouse-miRTarBase.txt > 13.txt & 
nohup python pick*py /home/mcb/malsha17/EvoByCompSel/parallel/Release-03/data/NETWORKS/Plant/BioGrid/input/Plant-BioGrid.txt > 14.txt & 
nohup python pick*py /home/mcb/malsha17/EvoByCompSel/parallel/Release-03/data/NETWORKS/Plant/PSICQUIC/input/Plant-PSICQUIC.txt > 15.txt & 
nohup python pick*py /home/mcb/malsha17/EvoByCompSel/parallel/Release-03/data/NETWORKS/Worm/BioGrid/input/Worm-BioGrid.txt > 16.txt & 
nohup python pick*py /home/mcb/malsha17/EvoByCompSel/parallel/Release-03/data/NETWORKS/Worm/Neural/input/Worm-Neural.txt > 17.txt & 
nohup python pick*py /home/mcb/malsha17/EvoByCompSel/parallel/Release-03/data/NETWORKS/Yeast/BioGrid/input/Yeast-BioGrid.txt > 18.txt & 
nohup python pick*py /home/mcb/malsha17/EvoByCompSel/parallel/Release-03/data/NETWORKS/Yeast/PSICQUIC/input/Yeast-PSICQUIC.txt > 19.txt & 
